/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as RaceStateRouteImport } from './routes/race.$state'
import { Route as StateStRouteImport } from './routes/state.$st'
import { Route as HouseStDistrictRouteImport } from './routes/house.$st.$district'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceStateRoute = RaceStateRouteImport.update({
  id: '/race/$state',
  path: '/race/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const StateStRoute = StateStRouteImport.update({
  id: '/state/$st',
  path: '/state/$st',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseStDistrictRoute = HouseStDistrictRouteImport.update({
  id: '/house/$st/$district',
  path: '/house/$st/$district',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/methodology': typeof MethodologyRoute
  '/trends': typeof TrendsRoute
  '/race/$state': typeof RaceStateRoute
  '/state/$st': typeof StateStRoute
  '/house/$st/$district': typeof HouseStDistrictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/methodology': typeof MethodologyRoute
  '/trends': typeof TrendsRoute
  '/race/$state': typeof RaceStateRoute
  '/state/$st': typeof StateStRoute
  '/house/$st/$district': typeof HouseStDistrictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/methodology': typeof MethodologyRoute
  '/trends': typeof TrendsRoute
  '/race/$state': typeof RaceStateRoute
  '/state/$st': typeof StateStRoute
  '/house/$st/$district': typeof HouseStDistrictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/methodology'
    | '/trends'
    | '/race/$state'
    | '/state/$st'
    | '/house/$st/$district'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/methodology'
    | '/trends'
    | '/race/$state'
    | '/state/$st'
    | '/house/$st/$district'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/methodology'
    | '/trends'
    | '/race/$state'
    | '/state/$st'
    | '/house/$st/$district'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MethodologyRoute: typeof MethodologyRoute
  TrendsRoute: typeof TrendsRoute
  RaceStateRoute: typeof RaceStateRoute
  StateStRoute: typeof StateStRoute
  HouseStDistrictRoute: typeof HouseStDistrictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race/$state': {
      id: '/race/$state'
      path: '/race/$state'
      fullPath: '/race/$state'
      preLoaderRoute: typeof RaceStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/$st': {
      id: '/state/$st'
      path: '/state/$st'
      fullPath: '/state/$st'
      preLoaderRoute: typeof StateStRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house/$st/$district': {
      id: '/house/$st/$district'
      path: '/house/$st/$district'
      fullPath: '/house/$st/$district'
      preLoaderRoute: typeof HouseStDistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  MethodologyRoute: MethodologyRoute,
  TrendsRoute: TrendsRoute,
  RaceStateRoute: RaceStateRoute,
  StateStRoute: StateStRoute,
  HouseStDistrictRoute: HouseStDistrictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
